package view;

import client.ChatClientManager;
import java.awt.BorderLayout;
import java.io.IOException;
import java.net.URL;
import java.util.jar.Manifest;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import view.panels.LoginJPanel;
import view.panels.UsersJPanel;

/**
 *
 * @author Guerino
 */
public class MainJFrame extends javax.swing.JFrame {
    private LoginJPanel loginPanel;
    private UsersJPanel userPanel;
    private String user;
    private String title;
    
    /**
     * Creates new form MainJFrameClient
     */
    public MainJFrame() {
        this.title = "AFI-Chat v";
        this.loginPanel = null;
        this.userPanel = null;
        
        initComponents();         
        setIconImage (new ImageIcon(getClass().getResource("/resources/messenger-icon-32.png")).getImage());
        
        printVersion();        
        //Centro el JFrame en la pantalla
        setLocationRelativeTo(null);
        
        this.loginPanel = new LoginJPanel(this);
        this.userPanel = new UsersJPanel(this);
        
        //Panel de Login por defecto
        setJPanel(0); 
        this.title = this.getTitle();
        
    } 
        
    /**
     * Establece el panel activo
     * @param panel 
     */
    public void setJPanel(int panel) {
        this.jPanelCliente.removeAll();
        this.jPanelCliente.setLayout(new java.awt.BorderLayout());
         //seteamos el panel a mostrar
        switch (panel) {
            case 0:                
                jPanelCliente.add(this.loginPanel,BorderLayout.CENTER);
                jMenuItemLogout.setVisible(false);
                break;
            case 1:                
                jPanelCliente.add(this.userPanel,BorderLayout.CENTER);
                jMenuItemLogout.setVisible(true);
                break;
        }
        this.pack();
        this.jPanelCliente.validate(); 
    }
    
    public UsersJPanel.UserJPanelListener getUserPanelListener(){
        return this.userPanel.getUserPanelListener();
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanelCliente = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemLogout = new javax.swing.JMenuItem();
        jMenuItemExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemAbout = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        javax.swing.GroupLayout jPanelClienteLayout = new javax.swing.GroupLayout(jPanelCliente);
        jPanelCliente.setLayout(jPanelClienteLayout);
        jPanelClienteLayout.setHorizontalGroup(
            jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 269, Short.MAX_VALUE)
        );
        jPanelClienteLayout.setVerticalGroup(
            jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 414, Short.MAX_VALUE)
        );

        jMenu1.setText("Archivo");

        jMenuItemLogout.setText("Cerrar sesion");
        jMenuItemLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLogoutActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemLogout);

        jMenuItemExit.setText("Salir");
        jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExitActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("?");

        jMenuItemAbout.setText("Acerca de...");
        jMenuItemAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAboutActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemAbout);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private void disconnect() {
        if(userPanel != null){
            //El protocolo esta armado en base a un archivo xml
            String xmlMensaje = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" +
                                "<message>" +
                                "<action>disconnect</action>" +
                                "<user><from>" + user + "</from>" +
                                "<from_port_id>"+ userPanel.getLocalPort() +"</from_port_id></user>" +
                                "</message>";

            // Enviamos un mensaje de desconexion al servidor
            this.userPanel.sendMessage(xmlMensaje);
        }
    }
    
    public void exit() {
        dispose();
        //Para asegurar la salida
        System.exit(0);
    }
    
    private void jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExitActionPerformed
        if(userPanel != null){
            userPanel.closeChatJframe();
        }
        
        //Nos deconectamos del servidor
        disconnect();
        //detiene el hilo de ejecucion del chat
        loginPanel.stopChat();
        exit();
    }//GEN-LAST:event_jMenuItemExitActionPerformed

    private void jMenuItemLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLogoutActionPerformed
        //Nos deconectamos del servidor
        disconnect();        
        userPanel.closeChatJframe();
        
        loginPanel.setLogueado(false);
        jMenuItemLogout.setVisible(false);
        this.setJPanel(0);
        
        this.setTitle(title + " UTN@FRC.2015");
    }//GEN-LAST:event_jMenuItemLogoutActionPerformed

    private void jMenuItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAboutActionPerformed
        // TODO add your handling code here:
        AboutJDialog about = new AboutJDialog(this, true);
        about.setTitle("Acerca de AFI Chat");
        //Centro el JFrame en la pantalla
        about.setLocationRelativeTo(this);
        about.setVisible(true);
    }//GEN-LAST:event_jMenuItemAboutActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // Si, se presiona el boton con la X de cerrar
        disconnect();
        
    }//GEN-LAST:event_formWindowClosing

    public String getUser() {
        return user;
    }

    public void setUser(String user) {
        this.user = user;
        this.setTitle("["+ user +"]-" + title);
    }    
    
    public void setUserPanelConnection(ChatClientManager client){
        //Acordarse de usar siempre la regla de los dos puntos para no violar el principio de encapsulamiento
        this.userPanel.setConnection(client, getUserPanelListener());
    }

    /**
    * Metodo encagargado de leer la version del manifest.mf
    */
    private void printVersion() {
        String jarFileURL = MainJFrame.class.getProtectionDomain().getCodeSource().getLocation().toString();
                       
        if(!jarFileURL.contains(".jar")){
            jarFileURL = "file:/D:/Arq.De.Sw-2015/AFI-ChatCliente/dist/AFI-ChatCliente.jar";
        }
        
        int pos = jarFileURL.indexOf("!");         
        if(pos != -1) {   
            jarFileURL = jarFileURL.substring(0,pos);  
        }
        
        if(!jarFileURL.startsWith("jar:")) {  
            jarFileURL = "jar:" + jarFileURL; 
        } 
        
        if(jarFileURL.lastIndexOf(".jar") != -1){
            URL manifestUrl; 
            try {

                manifestUrl = new URL(jarFileURL + "!/META-INF/MANIFEST.MF");
                Manifest manifest = new Manifest(manifestUrl.openStream());   

                if(manifest != null){
                    String str = title + manifest.getMainAttributes().getValue("Implementation-Version") 
                            + " (Build: " + manifest.getMainAttributes().getValue("Build-Number") 
                            + ", Compiled: "+  manifest.getMainAttributes().getValue("Built-Date") + ")";
                    setTitle(str);
                }
            }        
            catch (IOException ex) {
                Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemAbout;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JMenuItem jMenuItemLogout;
    private javax.swing.JPanel jPanelCliente;
    // End of variables declaration//GEN-END:variables
    
}