package view.panels;

import client.ChatClientManager;
import java.awt.Color;
import view.MainJFrame;
import view.RegisterJDialog;
import view.interfaces.ILoginJPanel;
import view.panels.controls.ImageJPanel;

/**
 *
 * @author Guerino
 */
public class LoginJPanel extends javax.swing.JPanel {
    private MainJFrame mainFrame;
    private ChatClientManager chClient;
    private volatile boolean logueado;
    
    /**
     * Creates new form LoginJPanel
     * @param frame
     */
    public LoginJPanel(MainJFrame frame) {
        this.mainFrame = frame;
        this.chClient = null;
        this.logueado = false;
        this.initComponents();        
        this.jLabelInfo.setText("");
        
        ((ImageJPanel)jPanelImageUser).setImagen("/resources/messenger-icon-128.png");      
    }
    
    /**
     * Color y texto para JLabelInfo
     * @param text texto a mostrar
     * @param color color del texto
     */
    private void setInfo(String text, Color color) {
        this.jLabelInfo.setForeground(color);
        this.jLabelInfo.setText(text);        
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldUser = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanelImageUser = new ImageJPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelNewRegister = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        jLabelInfo = new javax.swing.JLabel();

        jButtonLogin.setText("Iniciar sesion");
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Usuario");

        jTextFieldUser.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldUser.setText("Juan");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Iniciar sesion");

        jPanelImageUser.setPreferredSize(new java.awt.Dimension(128, 128));

        javax.swing.GroupLayout jPanelImageUserLayout = new javax.swing.GroupLayout(jPanelImageUser);
        jPanelImageUser.setLayout(jPanelImageUserLayout);
        jPanelImageUserLayout.setHorizontalGroup(
            jPanelImageUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelImageUserLayout.createSequentialGroup()
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 128, Short.MAX_VALUE))
        );
        jPanelImageUserLayout.setVerticalGroup(
            jPanelImageUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelImageUserLayout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Contraseña");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Inicie sesion con su cuenta o cree una.");

        jLabelNewRegister.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelNewRegister.setForeground(new java.awt.Color(0, 153, 204));
        jLabelNewRegister.setText("Regristarse.");
        jLabelNewRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelNewRegister.setDoubleBuffered(true);
        jLabelNewRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelNewRegisterMouseClicked(evt);
            }
        });

        jPasswordField.setText("juan");

        jLabelInfo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelInfo.setForeground(new java.awt.Color(204, 0, 0));
        jLabelInfo.setText("Label info");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelNewRegister))
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldUser)
                                    .addComponent(jPasswordField))
                                .addGap(13, 13, 13))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jPanelImageUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabelInfo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanelImageUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabelNewRegister))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jLabelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        this.setInfo("Conectando...", Color.BLACK);
        
        chClient = new ChatClientManager("127.0.0.1", 12345);
        if(chClient.isConnected()){
            //Para poder arrancar el hilo de recepcion de mensajes
            this.chClient.setListener(this.mainFrame.getUserPanelListener(), new LoginJPanelListener());
            
            //enviar al server el usuario y la clave y esperar un ok para continuar  
            String xmlMensaje = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" +
                                "<message>" +
                                "<action>connect</action>" +
                                "<user><name>" + jTextFieldUser.getText().trim() +"</name></user>" +
                                "<password>" + (new String(jPasswordField.getPassword())) +"</password>" +
                                "<port_id>" + chClient.getLocalPort() +"</port_id>" +
                                "</message>"; 
            
            this.chClient.sendText(xmlMensaje);
                        
        }else{
            this.setInfo("No se pudo conectar con el servidor.", Color.RED);
        }
    }//GEN-LAST:event_jButtonLoginActionPerformed

    /**
     * Metodo que se invoca desde la clase interna LoginJPanelListener en el metodo loginAccepted(), que
     * a su vez lo dispara el servidor al llegarle al cliente un mensaje de UPDATE
     */
    private void logueado() {
        this.setInfo("", Color.BLACK);
        //mostramos el panel de usuarios
        this.mainFrame.setJPanel(1);
         //Le pasamos la conexion al Panel de usuarios, para que interactue con el servidor
        this.mainFrame.setUserPanelConnection(chClient);
        
        this.mainFrame.setUser(this.jTextFieldUser.getText().trim());
        this.logueado = true;
    } 

    public void setLogueado(boolean logueado) {
        this.logueado = logueado;
    }
    
    private void jLabelNewRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelNewRegisterMouseClicked
        // Ventana de registro
        RegisterJDialog r = new RegisterJDialog(mainFrame, true);
        //RegisterJFrame r = new RegisterJFrame();
        r.setTitle("AFI Chat - Nuevo usuario");
        r.setLocationRelativeTo(this);
        r.setVisible(true);
    }//GEN-LAST:event_jLabelNewRegisterMouseClicked

    public void stopChat() {
        if(chClient != null)
             chClient.stop();
        
        this.logueado = false;
    }  
    
    class LoginJPanelListener implements ILoginJPanel {
        /**
         * Nota: el LoginJPanelListener al entrar al UserJPanel, se pone a null
         * por lo que este metodo solo se invoca desde doProcessUpdate una sola vez
         * al comienzo para loguearse
         */
        @Override
        public void loginAccepted() {       
           logueado();         
        }

        @Override
        public void setTexInfoLabel(String text) {
             setInfo(text, Color.RED);
        }
        
        @Override
        public boolean isLogueado() {
            return logueado;
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelInfo;
    private javax.swing.JLabel jLabelNewRegister;
    private javax.swing.JPanel jPanelImageUser;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTextField jTextFieldUser;
    // End of variables declaration//GEN-END:variables
}